DATA = {}
REGISTER = {}
WORD_SIZE = 4
MEMORY_BASE_ADDRESS = 256
INSTRUCTIONS = []
BUSY = True
FREE = False
STAGE = {
    'IF': FREE,
    'ID': FREE,
    'INTEGER': FREE,
    'FP_ADD': FREE,
    'FP_MUL': FREE,
    'FP_DIV': FREE,
    'WB': FREE
}
